# kibana config

server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "https://es01:9200", "https://es02:9200", "https://es03:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: kibana_system
elasticsearch.password: ${KIBANA_SYSTEM_USER_PASS}

## Browser to Kibana Encryption
#
server.ssl.enabled: true
server.ssl.certificate: "/usr/share/kibana/config/kibana-tls/kibana.crt"
server.ssl.key: "/usr/share/kibana/config/kibana-tls/kibana-key.pem"

## This configures Kibana to trust a specific Certificate Authority for connections to Elasticsearch
#
elasticsearch.ssl.certificateAuthorities: [ "/usr/share/kibana/config/kibana-tls/ca.crt" ]

