apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  storageClassName: mariadb-data
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  {{ if .Values.cloud }}
  gcePersistentDisk:
    pdName: mariadb-data
    fsType: ext4
  {{ else }}
  nfs:
    path: /mnt/thor/kube/mariadb-data
    server: 192.168.0.5
  {{ end }}