# Logstash Config

http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "https://es01:9200", "https://es02:9200", "https://es03:9200" ]

## X-Pack security credentials
#
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: "${LOGSTASH_SYSTEM_USER_PASS}"

## This configures logstash monitoring to trust a specific Certificate Authority for connections to Elasticsearch
#
xpack.monitoring.elasticsearch.ssl.certificate_authority: /usr/share/logstash/config/logstash-tls/ca.crt
