
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/CTFd/logins.log*
  fields:
    log_id: logins
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /var/log/CTFd/registrations.log*
  fields:
    log_id: registrations
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /var/log/CTFd/submissions.log*
  fields:
    log_id: submissions
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /var/log/CTFd/hints.log*
  fields:
    log_id: hints
  fields_under_root: true

filebeat.registry.path: /usr/share/filebeat/data/registry

output.logstash:
  enabled: true
  hosts: ["elk.int.ctf.issessions.ca:5044"]
  ssl.certificate_authorities: ["/usr/share/filebeat/ca.crt"]
  worker: 2
