all:
  children:
    internal:
      hosts:
        ctfd.int.ctf.issessions.ca: 
        elk.int.ctf.issessions.ca: 
    dmz:
      hosts:
        nginx.int.ctf.issessions.ca: 
        haproxy.int.ctf.issessions.ca: 
    elk:
      hosts:
        elk.int.ctf.issessions.ca:
          elk_git_repo_owner: abboudl
          elk_git_repo_name: S1-CTF-Services-ELK
      hosts:
        ctfd.int.ctf.issessions.ca: 
          ctfd_git_repo_owner: abboudl
          ctfd_git_repo_name: S2-CTF-Services-CTFd
    nginx:
      hosts:
        nginx.int.ctf.issessions.ca:
          nginx_git_repo_owner: abboudl
          nginx_git_repo_name: S3-CTF-Services-Nginx
    haproxy:
      hosts:
        haproxy.int.ctf.issessions.ca:
          haproxy_git_repo_owner: abboudl
          haproxy_git_repo_name: S4-CTF-Services-HAProxy  

        



