- hosts: vpn
  user: ansible
  become: yes
  
  tasks:
  - name: Create ctf user. Make them members of the sudo and docker groups. Set their shell to /bin/bash.
    user:
      name: ctf
      password: "{{ lookup('community.general.lastpass', 'ctf_user_pass', field='password') | password_hash('sha512') }}"
      shell: /bin/bash
      groups: docker,sudo
      append: yes

  - name: Upload the CTF administrator's public SSH key to the host allowing the CTF infrastructure administrator to login in as the ctf user from the administration VM.
    ansible.posix.authorized_key:
      user: ctf
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/ctf.pub') }}"

  - name: Transfer github private key to .ssh directory of ctf user. In effect, generate an identity (i.e. a private key) for the ctf user that allows them to clone private git repositories. 
    ansible.builtin.copy:
      src: "{{ lookup('env','HOME') + '/.ssh/ctf-repo-key' }}"
      dest: /home/ctf/.ssh/id_rsa
      owner: ctf
      group: ctf
      mode: '0600'
 
  - name: Transfer github public key to .ssh directory of ctf user.
    ansible.builtin.copy:
      src: "{{ lookup('env','HOME') + '/.ssh/ctf-repo-key.pub' }}"
      dest: /home/ctf/.ssh/id_rsa.pub
      owner: ctf
      group: ctf
      mode: '0600'
