- hosts: vpn
  user: ctf
  vars:
    wg_git_repo_owner: abboudl
    wg_git_repo_name: 2-CTF-Infra-Wireguard-VPN-Setup

  - name: Clone Wireguard VPN repository
    git:
      repo: "git@github.com:{{ wg_git_repo_owner }}/{{ wg_git_repo_name }}.git"
      dest: /home/ctf/ISSessionsCTF-Infra-Wireguard-VPN
      accept_hostkey: yes

  - name: Build Wireguard VPN image and start container
    community.docker.docker_compose:
      project_src: "/home/ctf/{{ wg_git_repo_name }}/"
      build: yes
      nocache: yes
      state: present
    register: output

  - ansible.builtin.debug:
      var: output
