version: '3.5'

services:
  nginx:
    container_name: ctf-nginx
    image: ctf-nginx:${NGINX_VERSION}
    build: 
      context: ./nginx/
      args:
        NGINX_VERSION: $NGINX_VERSION
    restart: unless-stopped
    ports : 
      - 80:8080
      - 443:8443
    volumes:
      # Nginx logs volume 
      - nginx-logs:/var/log/nginx/

  
  filebeat:
    container_name: ctf-filebeat
    image: ctf-filebeat:${ELK_VERSION}
    hostname: filebeat
    user: root
    build: 
      context: ./filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    restart: on-failure
    volumes:
      # Nginx logs volume 
      - nginx-logs:/var/log/nginx/
      # Named volume fbdata. This is used to persist the registry file between restarts, so to avoid data duplication
      - fbdata-nginx:/usr/share/filebeat/data/
    depends_on:
      - nginx

volumes:
  nginx-logs:
  fbdata-nginx:

