- hosts: ctfd
  user: ctf

  tasks:
    - name: Clone CTFd Github respository
      git:
        repo: "git@github.com:{{ chikp_git_repo_owner }}/{{ chikp_git_repo_name }}.git"
        dest: "/home/ctf/{{ chikp_git_repo_name }}"
        accept_hostkey: yes

    - name: >-
        Transfer secrets file containing CTFd secrets. Pull all secrets
        from password vault and populate ctfd-env-template.j2, then
        transfer the result.
      ansible.builtin.template:
        src: ./templates/ctfd-env-template.j2
        dest: "/home/ctf/{{ chikp_git_repo_name }}/S2-CTF-Services-CTFd/.env"
        owner: ctf
        group: ctf
        mode: '0600'

    - name: Copy CA certificate to filebeat directory on CTFd host
      ansible.builtin.copy:
        src: ./tls/ca/ca.crt
        dest: "/home/ctf/{{ chikp_git_repo_name }}/S2-CTF-Services-CTFd/filebeat/"
        owner: ctf
        group: ctf
        mode: '0600'

    - name: Build CTFd images (ctfd flask app, redis, and mariadb) and start containers
      community.docker.docker_compose:
        project_src: "/home/ctf/{{ chikp_git_repo_name }}/S2-CTF-Services-CTFd/"
        build: yes
        nocache: yes
        state: present
      register: output

    - ansible.builtin.debug:
        var: output


    
