#!/usr/bin/env bash

# Public Domain
PUBLIC_DOMAIN="issessions.ca"
PUBLIC_CTF_SUBDOMAIN="ctf"

# Region & Zone
GCP_PROJECT_ID="ctf-demo-project"
GCP_REGION="northamerica-northeast1"
GCP_ZONE="northamerica-northeast1-a"

# VPC and Subnets
VPC_NETWORK="issessions-ctf-vpc"
DMZ_SUBNET_ID="dmz-subnet"
DMZ_SUBNET_IP_RANGE="10.10.10.0/24"
INTERNAL_SUBNET_ID="internal-subnet"
INTERNAL_SUBNET_IP_RANGE="10.10.20.0/24"
INTERNAL_HOSTED_CHALLENGES_SUBNET_ID="hosted-challenges-cluster-subnet"
INTERNAL_HOSTED_CHALLENGES_SUBNET_IP_RANGE="10.10.30.0/24"

# Ansible Key Path
ANSIBLE_PUBLIC_KEY_PATH=~/.ssh/ansible.pub

# DNS Settings
INTERNAL_DNS_ZONE_ID="issessions-ctf-private-dns-zone"
INTERNAL_DNS_ZONE_DOMAIN="int.ctf.issessions.ca"

# Wireguard Host Settings
WG_HOST_ID="wireguard-int-ctf-issessions-ca"
WG_INTERNAL_HOSTNAME="wireguard" # will be prepended to .$INTERNAL_DNS_ZONE_DOMAIN
WG_INTERNAL_IP="10.10.10.7"
WG_MACHINE_TYPE="e2-small"
WG_MACHINE_IMAGE="ubuntu-2004-focal-v20210510"
WG_MACHINE_IMAGE_PROJECT="ubuntu-os-cloud"
WG_MACHINE_DISK_TYPE="pd-standard"
WG_MACHINE_DISK_SIZE="20GB"
WG_PROTOCOL="udp"
WG_PORT="51820"
WG_CLIENT_SUBNET="10.13.13.0/24"

# NGINX Host Settings
NGINX_HOST_ID="nginx-int-ctf-issessions-ca"
NGINX_INTERNAL_HOSTNAME="nginx" # will be prepended to .$INTERNAL_DNS_ZONE_DOMAIN to form FQDN
NGINX_INTERNAL_IP="10.10.10.8"
NGINX_MACHINE_TYPE="e2-custom-2-4096"
NGINX_MACHINE_IMAGE="ubuntu-2004-focal-v20210510"
NGINX_MACHINE_IMAGE_PROJECT="ubuntu-os-cloud"
NGINX_MACHINE_DISK_TYPE="pd-standard"
NGINX_MACHINE_DISK_SIZE="20GB"

# HAProxy Host Settings
HAPROXY_HOST_ID="haproxy-int-ctf-issessions-ca"
HAPROXY_INTERNAL_HOSTNAME="haproxy" # will be prepended to .$INTERNAL_DNS_ZONE_DOMAIN to form FQDN
HAPROXY_INTERNAL_IP="10.10.10.9"
HAPROXY_MACHINE_TYPE="e2-custom-2-2048"
HAPROXY_MACHINE_IMAGE="ubuntu-2004-focal-v20210510"
HAPROXY_MACHINE_IMAGE_PROJECT="ubuntu-os-cloud"
HAPROXY_MACHINE_DISK_TYPE="pd-standard"
HAPROXY_MACHINE_DISK_SIZE="20GB"

# CTFd Host Settings
CTFD_HOST_ID="ctfd-int-ctf-issessions-ca"
CTFD_INTERNAL_HOSTNAME="ctfd" # will be prepended to .$INTERNAL_DNS_ZONE_DOMAIN to form FQDN
CTFD_INTERNAL_IP="10.10.20.49"
CTFD_MACHINE_TYPE="e2-standard-4"
CTFD_MACHINE_IMAGE="ubuntu-2004-focal-v20210510"
CTFD_MACHINE_IMAGE_PROJECT="ubuntu-os-cloud"
CTFD_MACHINE_DISK_TYPE="pd-ssd"
CTFD_MACHINE_DISK_SIZE="200GB"

# ELK Host Settings
ELK_HOST_ID="elk-int-ctf-issessions-ca"
ELK_INTERNAL_HOSTNAME="elk" # will be prepended to .$INTERNAL_DNS_ZONE_DOMAIN to form FQDN
ELK_INTERNAL_IP="10.10.20.51"
ELK_MACHINE_TYPE="e2-standard-4"
ELK_MACHINE_IMAGE="ubuntu-2004-focal-v20210510"
ELK_MACHINE_IMAGE_PROJECT="ubuntu-os-cloud"
ELK_MACHINE_DISK_TYPE="pd-standard"
ELK_MACHINE_DISK_SIZE="200GB"
ES_PORT="9200"
LOGSTASH_BEATS_PORT="5044"
KIBANA_PORT="5601"

# Hosted Challenge Cluster Settings        
HOSTED_CHALLENGES_CLUSTER_ID="hosted-challenges-cluster"
HOSTED_CHALLENGES_CLUSTER_K8S_VERSION="1.18.17-gke.700"
HOSTED_CHALLENGES_CLUSTER_RELEASE_CHANNEL="stable"
HOSTED_CHALLENGES_CLUSTER_NODE_NUM="3"
HOSTED_CHALLENGES_CLUSTER_MACHINE_TYPE="e2-custom-2-16384"
HOSTED_CHALLENGES_CLUSTER_IMAGE_TYPE="COS_CONTAINERD"
HOSTED_CHALLENGES_CLUSTER_DISK_TYPE="pd-standard"
HOSTED_CHALLENGES_CLUSTER_DISK_SIZE="50GB"
HOSTED_CHALLENGES_NAMESPACE="hosted-challenges"

